### ISSUE TITLE
Public Release

### ISSUE THREAD

**Issue by m0mus** [eclipse-ee4j/glassfish-logging-annotation-processor#10]
Last CTS runs indicate no failures in this component. It's time to make a public release. Before the release make sure that Eclipse Release Review is passed and all dependencies have been released.

**Comment by senivam** [comment]
version 1.9 is in central:
https://repo1.maven.org/maven2/org/glassfish/annotations/logging-annotation-processor/1.9/
PR for release merge is: #13 

Issue can be closed
