### ISSUE TITLE
Build CI/CD pipeline

### ISSUE THREAD

**Issue by m0mus** [eclipse-ee4j/glassfish-logging-annotation-processor#3]
This task is for creating a basic build CI/CD pipeline for this project on Eclipse infrastructure. More information is here: https://ci.eclipse.org/.

**Comment by senivam** [comment]
master build:
https://jenkins.eclipse.org/glassfish/job/glassfish-logging-annotation-processor_master_build/
EE4J_8 build:
https://jenkins.eclipse.org/glassfish/job/glassfish-logging-annotation-processor_EE4J_build/
