### ISSUE TITLE
Integrate to GlassFish

### ISSUE THREAD

**Issue by m0mus** [eclipse-ee4j/glassfish-logging-annotation-processor#9]
- [ ] Integrate to Eclipse GlassFish
- [ ] Pass all CTS/TCK tests

#8 must be finished before starting working on this task.

**Comment by vinayvishal** [comment]
PR https://github.com/eclipse-ee4j/glassfish/pull/22663  raised.

**Comment by vinayvishal** [comment]
PR merged.
